name: Build Geode Mod
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

        - name: Android32
          os: ubuntu-latest
          target: Android32

        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          target: ${{ matrix.config.target }}

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        with: 
          delete-artifacts: false
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
          
  releasewnotes:
    name: Release
    runs-on: ubuntu-latest
    needs: ['package']
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        id: build
      - name: Get mod properties
        id: json_properties
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "mod.json"
      - uses: softprops/action-gh-release@v2
        name: "Release"
        with:
          tag_name: "${{steps.json_properties.outputs.version}}"
          files: "${{ package.steps.build.outputs.build-output }}/*"
          
